import "bindable_base.idl";
import "float3.idl";

namespace transformations
{
	runtimeclass mesh_vm : bindable_base
	{
		mesh_vm();

		//transformations.float3 scale;
		//Single scale;
		float3 scale;
	}
}
