import "bindable_base.idl";
import "float3.idl";

namespace transformations
{
	runtimeclass mesh_vm : bindable_base
	{
		mesh_vm();

		Windows.UI.Xaml.Input.StandardUICommand cmd_delete_mesh{ get; };

		Boolean is_selected;
		String mesh_type;
		UInt32 index;
		float3 scale;
		float3 translation;
		float3 rotation_axis;
		Single angle;
	}
}
