import "mvp_viewmodel.idl";
import "mesh_vm.idl";

namespace transformations
{
	[default_interface]
	runtimeclass model_view_projection : Windows.UI.Xaml.Controls.Page
	{
		model_view_projection();
		mvp_viewmodel vm{ get; };
		mesh_vm mesh_vm{ get; };
	}
}
